### ISSUE TITLE
What is taxii_endpoint for stix-import?

### ISSUE THREAD

**Issue by Waseem-farooqui** [ibm-security-intelligence/data-import#14]
I have a taxii server which have services `discovery`, `collection-management`, `poll` and `inbox`.
Now what is endpoint service is it discovery or collection or poll ?

**Comment by JasonKeirstead** [comment]
Hi! You want to point it at the root endpoint (remove the /poll portion)

**Comment by JasonKeirstead** [comment]
Let me know if you have any other questions.

**Comment by Waseem-farooqui** [comment]
Like I have services `/services/discovery` , `/services/poll` in this case my endpoint will be `/services` ?

**Comment by JasonKeirstead** [comment]
In this case it would be "/services".

**Comment by Waseem-farooqui** [comment]
Now when I run the script and specify the my **open-taxii Server** ip it throws.

```
Invalid reponse from TAXII server
{'extended_headers': {},
'in_response_to': '0',
'message': 'HTTP Error 404: NOT FOUND\r\nServer: gunicorn/19.4.5\r\nDate: Thu, 24 Mar 2016 12:21:43 GMT\r\nConnection: close\r\nContent-Type: text/html\r\nContent-Length: 233\r\n\r\n<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>\n',
'message_id': '0',
'message_type': 'Status_Message',
'status_detail': {},
'status_type': 'FAILURE'}
```

This was my script 
`sudo python ./import_stix.py -i 172.20.16.54 -t 6f178fb7-9c1c-4ecc-b8b9-8b5dcaf9b790 -x 172.20.16.36 -p 9000 --taxii_endpoint /services -y IPv4 Address -c collection-A -r Asset Reconciliation IPv4 Whitelist`

While in case when I specify the **hailataxii.com** it works fine.
`sudo python ./import_stix.py -i 172.20.16.54 -t 6f178fb7-9c1c-4ecc-b8b9-8b5dcaf9b790 -x 172.20.16.36 -p 9000 --taxii_endpoint /services -y IPv4 Address -c collection-A -r Asset Reconciliation IPv4 Whitelist
`
And I don't even see any request on the taxii server.

**Comment by JasonKeirstead** [comment]
It looks like the way this is structured won't work with OpenTaxii without me making some changes. I will try to do an update today.

As a reminder as well, as of QRadar 7.2.6 this script is deprecated; the suggested course is to use the supported Threat Intelligence application (located here https://exchange.xforce.ibmcloud.com/hub/extension/IBMQRadar:ThreatIntelligence). Since this application uses TAXII discover, it would not have this issue.

**Comment by Waseem-farooqui** [comment]
Ok my end goal is to integrate the taxii server with Threat Intelligence app.
But I have a same problem here in which i need your guidance for **endpoint**  i will use the same `/service` because this app works fine in case of **hailataxii** but in my **opentaxii** server case it throws `Bad Gateway`.
Will you please help me out :(

**Comment by JasonKeirstead** [comment]
Hi Waseem - in the Threat Intelligence app the endpoint should point at your discovery service. The app will then perform a discovery and ask  you what to poll. If you are getting a Bad Gateway message it could mean any number of things including a self-signed certificates (the app requires fully valid certificates for an SSL connection. 

You should open a PMR with IBM Support if you are having issues with this app.

**Comment by Waseem-farooqui** [comment]
Which means in my case it should be at `/services/discovery`.
![Uploading Screenshot from 2016-03-24 19:56:42.png…]()

**OpenTaxii** throws error on this request 

    {"level": "info", "timestamp": "2016-03-24T14:56:32.588731Z", "event": "Processing message",   "message_version": "urn:taxii.mitre.org:message:xml:1.1", "service_id": "discovery_a", "logger": "opentaxii.taxii.services.discovery.DiscoveryService", "message_type": "Discovery_Request", "message_id": "a0066582-98ab-4e1f-bc36-121076e21a84"}
    {"level": "info", "timestamp": "2016-03-24T14:56:32.628368Z", "event": "Processing message", "message_version": "urn:taxii.mitre.org:message:xml:1.1", "service_id": "discovery_a", "logger": "opentaxii.taxii.services.discovery.DiscoveryService", "message_type": "Collection_Information_Request", "message_id": "1"}
    {"level": "warning", "timestamp": "2016-03-24T14:56:32.628632Z", "event": "Message not supported", "message_version": "urn:taxii.mitre.org:message:xml:1.1", "service_id": "discovery_a", "logger": "opentaxii.taxii.services.discovery.DiscoveryService", "message_type": "Collection_Information_Request", "message_id": "1"}
    {"exception": "Traceback (most recent call last):\n  File \"/home/waseem/venv/local/lib/python2.7/site-packages/flask/app.py\", line 1475, in full_dispatch_request\n    
    rv = self.dispatch_request()\n  
    File \"/home/waseem/venv/local/lib/python2.7/site-packages/flask/app.py\", line 1461, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/home/waseem/venv/local/lib/python2.7/site-packages/opentaxii/middleware.py\", line 73, in wrapper\n    return _process_with_service(service)\n  
    File \"/home/waseem/venv/local/lib/python2.7/site-packages/opentaxii/middleware.py\", line 146, in _process_with_service\n    response_message = service.process(request.headers, taxii_message)\n  
    File \"/home/waseem/venv/local/lib/python2.7/site-packages/opentaxii/taxii/services/abstract.py\", line 70, in process\n    handler = self.get_message_handler(message)\n  
    File \"/home/waseem/venv/local/lib/python2.7/site-packages/opentaxii/taxii/services/abstract.py\", line 96, in get_message_handler\n    in_response_to=message.message_id)\n  
    File \"/home/waseem/venv/local/lib/python2.7/site-packages/opentaxii/taxii/services/abstract.py\", line 91, in get_message_handler\n    return self.handlers[message.message_type]\nFailureStatus: 'Collection_Information_Request'", "level": "warning", "timestamp": "2016-03-24T14:56:32.628878Z", "logger": "opentaxii.middleware", "event": "Status exception"}

Now first thing is to write a certificate for the ssl communication ?

**Comment by JasonKeirstead** [comment]
Please open a PMR with IBM Support to troubleshoot this application.
