### ISSUE TITLE
Error executing stix_import.py

### ISSUE THREAD

**Issue by ashbyca** [ibm-security-intelligence/data-import#8]
After downloading and install required dependencies received the following error:

Traceback (most recent call last):
  File "stix_import.py", line 293, in <module>
    main()
  File "stix_import.py", line 185, in main
    vocabs._VOCAB_MAP["stixVocabs:IndicatorTypeVocab-1.0"] = IndicatorType
AttributeError: 'module' object has no attribute '_VOCAB_MAP'

Currently running python v2.7.10_2 on OSX v10.10.5 with the following dependencies:
stix (1.2.0.1.dev2)
pytz (2015.4)
libtaxii (1.1.107)

**Comment by ibmcraigroberts** [comment]
So I am running into the same issue, if you know your STIX formats are definitely 1.1 then you can remove or hash out line 185. 

`vocabs._VOCAB_MAP["stixVocabs:IndicatorTypeVocab-1.0"] = IndicatorType`

The script will run correctly then, I am not sure if they have updated the python stix lib to depreciate 1.0 or something. @JasonKeirstead might be able to shed some light on it.

**Comment by JasonKeirstead** [comment]
Hi

When I made this script there was a lot of both 1.0 and 1.1 content in the wild so I was attempting to support both with this, as the MITRE code only supports 1.1+ even though QRadar doesn't care.

I'll take a look at this on Monday.

**Comment by ashbyca** [comment]
Thanks, removing line 185 resolves the issue.
